//TV SHOW SEARCHER
export const SEARCH_SHOW = "SEARCH_SHOW";
export const ON_OFF_LOADER = "ON_OFF_LOADER";
export const CLEAR_SHOWS = "CLEAR_SHOWS";

//WEATHER
export const READ_WEATHER = "READ_WEATHER";
export const SEARCH_LOCAL_WEATHER = "SEARCH_LOCAL_WEATHER";
export const SEARCH_INPUT_WEATHER = "SEARCH_INPUT_WEATHER";
export const SET_WEATHER_LOADING = "SET_WEATHER_LOADING";

//TO DO LIST
export const READ_USER = "READ_USER";
export const SWITCH_LOGG_METHOD = "SWITCH_LOGG_METHOD";
export const READ_TASKS = "READ_TASKS";
export const CREATE_TASK_WITH_FILE = "CREATE_TASK_WITH_FILE";
export const CREATE_TASK_NO_FILE = "CREATE_TASK_NO_FILE";
export const SELECT_TASK_TO_UPDATE = "SELECT_TASK_TO_UPDATE";
export const UPDATE_TASK_WITH_FILE = "UPDATE_TASK_WITH_FILE";
export const UPDATE_TASK_NO_FILE = "UPDATE_TASK_NO_FILE";
export const DELETE_TASK = "DELETE_TASK";
export const SHOW_LOADER = "SHOW_LOADER";
export const CLEAR_LIST = "CLEAR_LIST";

//SHOPPING CART
export const READ_SHOP_DATA = "READ_DATA";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART:";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART:";
export const CLEAR_CART = "CLEAR_CART";
export const CLEAR_SHOP = "CLEAR_SHOP";
export const SET_SHOP_LOADING = "SET_SHOP_LOADING";
export const SET_SHOP_ERROR = "SET_SHOP_ERROR";
